/**
 * Skills Base application programming interface (API)
 * Restful API to manage the Seed Application to be used as an example.
 *
 * OpenAPI spec version: V1.0
 * Contact: alfonsoserra@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Skill {
  children?: Array<Skill>;

  comments?: string;

  /**
   * Skill ID
   */
  id?: number;

  level?: number;

  position?: number;

  text?: string;

  type?: Skill.TypeEnum;

  interest?: number;
  proficiency?: number;

  isProficiencyAssessed?: boolean;
  isInterestAssessed?: boolean;


  averageInterest?: number;
  averageProficiency?: number;
}

export namespace Skill {
  export type TypeEnum = 'category' | 'skill';
}


