/**
 * Skills Base application programming interface (API)
 * Restful API to manage the Seed Application to be used as an example.
 *
 * OpenAPI spec version: V1.0
 * Contact: alfonsoserra@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserRate } from './user-rate';

export interface UserRateSummary {

  topTenByInterest?: Array<UserRate>;
  topTenByProficiency?: Array<UserRate>;

}


